// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbvykjzlckghiyzcvsus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidnlranpsY2tnaGl5emN2c3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTk5OTUsImV4cCI6MjA3MjEzNTk5NX0.tnMNZxKVm_d8YP7EmIXPjCFCvIsWT61oszhYB5ix_i8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});